services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        REQUIREMENTS: requirements.txt
    image: proyectoo-web:dev
    env_file:
      - .env
    environment:
      FLASK_ENV: development
      APP_ENV: development
      DB_HOST: 10.62.115.242
      DB_PORT: 3306
    command: >
      sh -c "flask --app wsgi run --host=0.0.0.0 --port=8000 --debug"
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
