services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: proyectoo-web:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      APP_ENV: production
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
